name: tiebreak

on: [push]

jobs:
  rxdb-supabase:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm ci

      - name: Dependencies audit
        run: npm audit --audit-level=moderate --omit=dev

      - name: Build
        run: npm run build

      - name: Format check
        run: npm run format:check

      - name: Lint check
        run: npm run lint:check

      - name: Spell check
        run: npm run spell:check

      - name: Tests
        run: npm run test
